import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# 1. FETCH HISTORICAL DATA
# Using Apple Inc. (AAPL) as a robust testing target
ticker = "AAPL"
print(f"Fetching data for {ticker}...")
df = yf.download(ticker, start="2018-01-01", end="2026-01-01")

# Clean multi-index columns if generated by yfinance
df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

# 2. FEATURE ENGINEERING (AI Inputs)
# Calculate Technical Indicators to feed into the algorithm
df['Return'] = df['Close'].pct_change()
df['SMA_10'] = df['Close'].rolling(window=10).mean()
df['SMA_50'] = df['Close'].rolling(window=50).mean()

# Relative Strength Index (RSI)
delta = df['Close'].diff()
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
rs = gain / (loss + 1e-9)
df['RSI'] = 100 - (100 / (1 + rs))

# Volatility (Rolling Standard Deviation)
df['Volatility'] = df['Return'].rolling(window=10).std()

# Drop rows with NaN values resulting from moving windows
df.dropna(inplace=True)

# 3. DEFINE TARGET (What the AI learns to predict)
# Target: 1 if tomorrow's close price is higher than today's close, else 0
df['Target'] = np.where(df['Close'].shift(-1) > df['Close'], 1, 0)

# Define feature columns used for prediction
features = ['Close', 'SMA_10', 'SMA_50', 'RSI', 'Volatility', 'Return']
X = df[features]
y = df['Target']

# 4. TRAIN/TEST SPLIT
# We split chronologically (shuffle=False) to avoid looking into the future
X_train, X_test, y_train, y_test = train_test_split(X, y, test_split=0.2, shuffle=False)

# 5. INITIALIZE AND TRAIN THE AI MODEL
# Random Forest matches the robust, ensemble nature of XGBoost
model = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=7)
model.fit(X_train, y_train)

# 6. EVALUATE THE ALGORITHM
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("\n--- Model Performance Summary ---")
print(f"Out-of-Sample Accuracy Score: {accuracy:.2%}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 7. GENERATE TRADING SIGNALS FOR THE NEXT DAY
latest_features = X.tail(1)
next_day_prediction = model.predict(latest_features)[0]
probability = model.predict_proba(latest_features)[0]

print("\n--- Live Trading Dashboard ---")
if next_day_prediction == 1:
    print(f"🚀 AI SIGNAL: BUY / LONG position recommended for {ticker}")
    print(f"Confidence Level: {probability[1]:.2%}")
else:
    print(f"📉 AI SIGNAL: SELL / SHORT position recommended for {ticker}")
    print(f"Confidence Level: {probability[0]:.2%}")
